import jsPDF from 'jspdf';
import type { Group, Task, ActivityLog, GroupMember, Evidence } from '@/types';

// ── Helpers ──────────────────────────────────────────────────────────────────

function fmtDate(iso: string | null): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function fmtDateTime(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function actionLabel(action: string, meta: Record<string, unknown> | null): string {
  switch (action) {
    case 'task_created':  return `Created task: ${meta?.task_title ?? ''}`;
    case 'task_assigned': return `Assigned task: ${meta?.task_title ?? ''}`;
    case 'task_updated':  return `Updated task: ${meta?.task_title ?? ''}`;
    case 'task_done':     return `Completed task: ${meta?.task_title ?? ''}`;
    case 'file_uploaded': return `Uploaded evidence for: ${meta?.task_title ?? ''}`;
    case 'member_joined': return 'Joined the group';
    default: return action;
  }
}

// ── Layout constants ─────────────────────────────────────────────────────────

const PW  = 210;   // A4 width mm
const PH  = 297;   // A4 height mm
const ML  = 16;    // margin left
const MR  = 16;    // margin right
const CW  = PW - ML - MR;  // 178mm content width

// Brand colours (used sparingly)
const ORANGE  = [255, 88, 65]   as const;  // #FF5841
const ORANGE_LIGHT = [255, 240, 238] as const;  // #FFF0EE
const GRAY_DARK   = [30, 30, 30]  as const;
const GRAY_MID    = [90, 90, 90]  as const;
const GRAY_LIGHT  = [160, 160, 160] as const;
const GRAY_RULE   = [220, 220, 220] as const;
const GRAY_ROW    = [248, 248, 248] as const;

// ── Drawing helpers ───────────────────────────────────────────────────────────

function setColor(doc: jsPDF, rgb: readonly [number, number, number]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

function sectionHeader(doc: jsPDF, label: string, y: number): number {
  // Light orange pill behind label
  doc.setFillColor(ORANGE_LIGHT[0], ORANGE_LIGHT[1], ORANGE_LIGHT[2]);
  doc.roundedRect(ML, y - 4.5, CW, 8, 1.5, 1.5, 'F');

  // Small orange square accent
  doc.setFillColor(ORANGE[0], ORANGE[1], ORANGE[2]);
  doc.rect(ML, y - 3.5, 2.5, 6, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  setColor(doc, GRAY_DARK);
  doc.text(label, ML + 5, y);
  return y + 7;
}

function checkPage(doc: jsPDF, y: number, needed = 12): { doc: jsPDF; y: number } {
  if (y + needed > PH - 18) {
    doc.addPage();
    return { doc, y: 18 };
  }
  return { doc, y };
}

// ── Main export ───────────────────────────────────────────────────────────────

export function generateReport(
  group: Group,
  members: GroupMember[],
  tasks: Task[],
  activity: ActivityLog[],
  evidenceByTask: Record<string, Evidence[]> = {}
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = 18;

  // ── Header ─────────────────────────────────────────────────────────────────

  // Orange top bar
  doc.setFillColor(ORANGE[0], ORANGE[1], ORANGE[2]);
  doc.rect(0, 0, PW, 10, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  setColor(doc, GRAY_DARK);
  doc.text('Group Contribution Report', ML, y);
  y += 7;

  // Subtitle / meta line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  setColor(doc, GRAY_MID);
  doc.text(`Generated by Contrib  ·  ${fmtDate(new Date().toISOString())}`, ML, y);
  y += 6;

  // Thin rule
  doc.setDrawColor(GRAY_RULE[0], GRAY_RULE[1], GRAY_RULE[2]);
  doc.line(ML, y, PW - MR, y);
  y += 8;

  // ── Group details ───────────────────────────────────────────────────────────

  y = sectionHeader(doc, 'Group Details', y);
  y += 3;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);

  const details: [string, string][] = [
    ['Group name', group.name],
    ['Subject',    group.subject],
    ['Due date',   fmtDate(group.due_date)],
    ['Report generated', fmtDateTime(new Date().toISOString())],
  ];

  details.forEach(([label, value]) => {
    setColor(doc, GRAY_MID);
    doc.text(label, ML + 2, y);
    setColor(doc, GRAY_DARK);
    doc.text(value, ML + 42, y);
    y += 5.5;
  });

  y += 6;

  // ── Member contribution table ───────────────────────────────────────────────

  ({ y } = checkPage(doc, y, 40));
  y = sectionHeader(doc, 'Member Contribution Summary', y);
  y += 4;

  // Column widths — must sum to CW (178)
  // name:65  assigned:33  done:30  completion:50  → 178 ✓
  const colName       = 65;
  const colAssigned   = 33;
  const colDone       = 30;
  // colCompletion    = 50 (remainder)

  // Right-edge x positions for right-aligned number columns
  const xName       = ML + 2;
  const xAssigned   = ML + colName + colAssigned - 3;
  const xDone       = ML + colName + colAssigned + colDone - 3;
  const xCompletion = ML + CW - 3;

  // y = top of row throughout this section (not text baseline)
  const ROW_H = 7;    // row height in mm
  const TY    = 4.5;  // offset from row top to text baseline

  // Header row
  doc.setFillColor(235, 235, 235);
  doc.rect(ML, y, CW, ROW_H + 1, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  setColor(doc, GRAY_DARK);
  doc.text('Member',     xName,       y + TY);
  doc.text('Assigned',   xAssigned,   y + TY, { align: 'right' });
  doc.text('Done',       xDone,       y + TY, { align: 'right' });
  doc.text('Completion', xCompletion, y + TY, { align: 'right' });
  y += ROW_H + 1;

  // Data rows — y is always the top of the current row
  members.forEach((m, idx) => {
    ({ y } = checkPage(doc, y, ROW_H + 2));

    const memberTasks = tasks.filter((t) => t.assignee_id === m.profile_id);
    const doneTasks   = memberTasks.filter((t) => t.status === 'done');
    const pct         = memberTasks.length > 0
      ? Math.round((doneTasks.length / memberTasks.length) * 100) : 0;
    const name        = m.profile?.name ?? m.profile_id;
    const isLead      = m.profile_id === group.lead_id;

    // Alternating row background (fills the full row, no overlap)
    if (idx % 2 === 0) {
      doc.setFillColor(GRAY_ROW[0], GRAY_ROW[1], GRAY_ROW[2]);
      doc.rect(ML, y, CW, ROW_H, 'F');
    }

    const ty = y + TY;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    setColor(doc, GRAY_DARK);
    doc.text(isLead ? `${name} (Lead)` : name, xName, ty, { maxWidth: colName - 4 });

    setColor(doc, GRAY_MID);
    doc.text(String(memberTasks.length), xAssigned, ty, { align: 'right' });

    if (doneTasks.length > 0) {
      doc.setTextColor(22, 163, 74);
    } else {
      setColor(doc, GRAY_LIGHT);
    }
    doc.text(String(doneTasks.length), xDone, ty, { align: 'right' });

    if (pct === 100) {
      doc.setTextColor(ORANGE[0], ORANGE[1], ORANGE[2]);
    } else {
      setColor(doc, GRAY_DARK);
    }
    doc.text(`${pct}%`, xCompletion, ty, { align: 'right' });

    y += ROW_H;

    // Row divider at exact bottom of row
    doc.setDrawColor(GRAY_RULE[0], GRAY_RULE[1], GRAY_RULE[2]);
    doc.line(ML, y, PW - MR, y);
  });

  y += 8;

  // ── Per-member task details ─────────────────────────────────────────────────

  ({ y } = checkPage(doc, y, 20));
  y = sectionHeader(doc, 'Per-Member Task Details', y);
  y += 4;

  members.forEach((m) => {
    const name = m.profile?.name ?? m.profile_id;
    const completedTasks = tasks.filter(
      (t) => t.assignee_id === m.profile_id && t.status === 'done'
    );
    const allMemberTasks = tasks.filter((t) => t.assignee_id === m.profile_id);

    ({ y } = checkPage(doc, y, 16));

    // Member name subheader
    doc.setFillColor(245, 245, 245);
    doc.rect(ML, y - 3.5, CW, 6.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    setColor(doc, GRAY_DARK);
    doc.text(name, ML + 2, y);

    // Mini stats on the right
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    setColor(doc, GRAY_MID);
    doc.text(
      `${completedTasks.length}/${allMemberTasks.length} tasks done`,
      PW - MR - 2,
      y,
      { align: 'right' }
    );
    y += 7;

    if (completedTasks.length === 0) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8.5);
      setColor(doc, GRAY_LIGHT);
      doc.text('No completed tasks.', ML + 4, y);
      y += 5;
    } else {
      completedTasks.forEach((t) => {
        ({ y } = checkPage(doc, y, 10));

        // Orange bullet + title
        doc.setFillColor(ORANGE[0], ORANGE[1], ORANGE[2]);
        doc.circle(ML + 3, y - 1, 0.8, 'F');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        setColor(doc, GRAY_DARK);
        doc.text(t.title, ML + 6, y, { maxWidth: CW - 6 });
        y += 4;

        // Sub-line: completed date (left) + evidence versions (right)
        doc.setFontSize(7.5);
        if (t.completed_at) {
          setColor(doc, GRAY_LIGHT);
          doc.text(`Completed ${fmtDateTime(t.completed_at)}`, ML + 6, y);
        }
        const taskEvidence = evidenceByTask[t.id] ?? [];
        if (taskEvidence.length > 0) {
          const label = `[evidence — ${taskEvidence.map((e) => `v${e.version_number}`).join(', ')}]`;
          doc.setTextColor(22, 163, 74);
          doc.text(label, PW - MR - 2, y, { align: 'right' });
        } else {
          setColor(doc, GRAY_LIGHT);
          doc.text('[no evidence]', PW - MR - 2, y, { align: 'right' });
        }

        setColor(doc, GRAY_DARK);
        y += 5.5;
      });
    }
    y += 4;
  });

  // ── Activity timeline ───────────────────────────────────────────────────────

  ({ y } = checkPage(doc, y, 20));
  y = sectionHeader(doc, 'Full Activity Timeline', y);
  y += 4;

  const TIME_COL = 38;
  const ACTOR_COL = 36;

  // Column labels
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  setColor(doc, GRAY_MID);
  doc.text('Date & Time', ML + 2, y);
  doc.text('Member', ML + TIME_COL + 2, y);
  doc.text('Action', ML + TIME_COL + ACTOR_COL + 2, y);
  y += 4;

  doc.setDrawColor(GRAY_RULE[0], GRAY_RULE[1], GRAY_RULE[2]);
  doc.line(ML, y, PW - MR, y);
  y += 3;

  const sorted = [...activity].sort(
    (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()
  );

  sorted.forEach((entry, idx) => {
    ({ y } = checkPage(doc, y, 6));

    const actor = entry.actor?.name ?? entry.actor_id;
    const label = actionLabel(entry.action, entry.meta as Record<string, unknown> | null);

    if (idx % 2 === 0) {
      doc.setFillColor(GRAY_ROW[0], GRAY_ROW[1], GRAY_ROW[2]);
      doc.rect(ML, y - 3.5, CW, 5.5, 'F');
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);

    setColor(doc, GRAY_LIGHT);
    doc.text(fmtDateTime(entry.created_at), ML + 2, y);

    setColor(doc, GRAY_MID);
    doc.text(actor, ML + TIME_COL + 2, y, { maxWidth: ACTOR_COL - 2 });

    setColor(doc, GRAY_DARK);
    doc.text(label, ML + TIME_COL + ACTOR_COL + 2, y, { maxWidth: CW - TIME_COL - ACTOR_COL - 2 });

    y += 5.5;
  });

  // ── Footer (every page) ─────────────────────────────────────────────────────

  const pageCount = (doc as jsPDF & { internal: { getNumberOfPages: () => number } })
    .internal.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    // Bottom orange line
    doc.setFillColor(ORANGE[0], ORANGE[1], ORANGE[2]);
    doc.rect(0, PH - 8, PW, 8, 'F');
    // Footer text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(255, 255, 255);
    doc.text(
      `Generated by Contrib  ·  Activity data is automatically recorded  ·  Page ${i} of ${pageCount}`,
      PW / 2,
      PH - 3,
      { align: 'center' }
    );
  }

  doc.save(`contrib-report-${group.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}
