import jsPDF from 'jspdf';
import type { Group, Task, ActivityLog, GroupMember } from '@/types';

function formatDate(iso: string | null): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

function formatDateTime(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function actionLabel(action: string, meta: Record<string, unknown> | null): string {
  switch (action) {
    case 'task_created': return `Created task: ${meta?.task_title ?? ''}`;
    case 'task_assigned': return `Assigned task: ${meta?.task_title ?? ''}`;
    case 'task_done': return `Completed task: ${meta?.task_title ?? ''}`;
    case 'file_uploaded': return `Uploaded evidence for: ${meta?.task_title ?? ''}`;
    case 'member_joined': return 'Joined the group';
    default: return action;
  }
}

export function generateReport(
  group: Group,
  members: GroupMember[],
  tasks: Task[],
  activity: ActivityLog[]
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const PW = 210;
  const ML = 15;
  const MR = 15;
  const CW = PW - ML - MR;
  let y = 15;

  // ── Header ────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Group Contribution Report', ML, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by Contrib · ${formatDate(new Date().toISOString())}`, ML, y);
  y += 8;

  doc.setDrawColor(200);
  doc.line(ML, y, PW - MR, y);
  y += 6;

  // ── Group info ────────────────────────────────────────
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Group Details', ML, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${group.name}`, ML, y); y += 5;
  doc.text(`Subject: ${group.subject}`, ML, y); y += 5;
  doc.text(`Due Date: ${formatDate(group.due_date)}`, ML, y); y += 5;
  doc.text(`Export Date: ${formatDateTime(new Date().toISOString())}`, ML, y);
  y += 10;

  // ── Member summary table ──────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Member Contribution Summary', ML, y);
  y += 7;

  // Table header
  const colWidths = [60, 30, 30, 30];
  const headers = ['Member', 'Assigned', 'Done', 'Completion'];
  doc.setFontSize(9);
  doc.setFillColor(240, 240, 240);
  doc.rect(ML, y - 4, CW, 7, 'F');
  let x = ML;
  headers.forEach((h, i) => {
    doc.setFont('helvetica', 'bold');
    doc.text(h, x + 2, y);
    x += colWidths[i];
  });
  y += 5;

  // Table rows
  members.forEach((m) => {
    const memberTasks = tasks.filter((t) => t.assignee_id === m.profile_id);
    const doneTasks = memberTasks.filter((t) => t.status === 'done');
    const pct = memberTasks.length > 0
      ? Math.round((doneTasks.length / memberTasks.length) * 100)
      : 0;
    const name = m.profile?.name ?? m.profile_id;

    x = ML;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(name, x + 2, y); x += colWidths[0];
    doc.text(String(memberTasks.length), x + 2, y); x += colWidths[1];
    doc.text(String(doneTasks.length), x + 2, y); x += colWidths[2];
    doc.text(`${pct}%`, x + 2, y);
    y += 6;

    doc.setDrawColor(230);
    doc.line(ML, y - 1, PW - MR, y - 1);
  });

  y += 6;

  // ── Per-member task sections ──────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Per-Member Task Details', ML, y);
  y += 7;

  members.forEach((m) => {
    const name = m.profile?.name ?? m.profile_id;
    const memberTasks = tasks.filter((t) => t.assignee_id === m.profile_id && t.status === 'done');

    if (y > 260) { doc.addPage(); y = 15; }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(name, ML, y);
    y += 5;

    if (memberTasks.length === 0) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('No completed tasks.', ML + 4, y);
      doc.setTextColor(0);
      y += 5;
    } else {
      memberTasks.forEach((t) => {
        if (y > 270) { doc.addPage(); y = 15; }
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(0);
        doc.text(`• ${t.title}`, ML + 4, y);
        doc.setTextColor(120);
        doc.text(`Completed: ${formatDateTime(t.completed_at!)}`, ML + 90, y);
        if (t.evidence_url) {
          doc.setTextColor(80, 80, 200);
          doc.text(`[evidence]`, ML + 160, y);
        }
        doc.setTextColor(0);
        y += 5;
      });
    }
    y += 3;
  });

  // ── Full activity timeline ────────────────────────────
  if (y > 240) { doc.addPage(); y = 15; }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text('Full Activity Timeline', ML, y);
  y += 7;

  const sorted = [...activity].sort(
    (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()
  );

  sorted.forEach((entry) => {
    if (y > 275) { doc.addPage(); y = 15; }
    const actor = entry.actor?.name ?? entry.actor_id;
    const label = actionLabel(entry.action, entry.meta as Record<string, unknown> | null);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(0);
    doc.text(`${formatDateTime(entry.created_at)}`, ML, y);
    doc.text(`${actor} — ${label}`, ML + 40, y);
    y += 5;
  });

  y += 8;

  // ── Footer ────────────────────────────────────────────
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    'Generated by Contrib · Activity data is automatically recorded',
    PW / 2,
    285,
    { align: 'center' }
  );

  doc.save(`contrib-report-${group.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}
